database:
  driverClass: org.h2.Driver
  user: sa
  password: password
  url: jdbc:h2:mem:testdb
  properties:
    hibernate.hbm2ddl.auto: create

server:
  maxThreads: 128
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

jwt:
  issuer: starterkit
  secret: 123456
  lifetime: '30 days'